[rule]
id = "python-no-fixme-comments"
description = "Disallow FIXME comments in Python code"
severity = "warning"

[match]
language = "python"
query = """
((comment) @violation
 (#match? @violation "(?i)FIXME"))
"""
